# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Brand.create(name: "Lush")
Brand.create(name: "BioBag")
Brand.create(name: "Seventh Generation")
Brand.create(name: "Patagonia")
Brand.create(name: "Grow NYC")
Brand.create(name: "IKEA")
Brand.create(name: "Trader Joe's")
Brand.create(name: "Tom's")
Brand.create(name: "Coyuchi")
Brand.create(name: "Youth to the People")
Brand.create(name: "United by Blue")
Brand.create(name: "Avocado Mattress")
Brand.create(name: "Viori")
Brand.create(name: "Grin Natural")
Brand.create(name: "Bite")
Brand.create(name: "Blue Land")
Brand.create(name: "GoPurePod")
Brand.create(name: "Kapanui Nails")
Brand.create(name: "NetZero Company")

Category.create(name: "Beauty")
Category.create(name: "Compostable")
Category.create(name: "Cleaning products")
Category.create(name: "Clothing")
Category.create(name: "Furniture")
Category.create(name: "Groceries")
Category.create(name: "Shoes")
Category.create(name: "Home")
Category.create(name: "Skin care")
Category.create(name: "Travel")
Category.create(name: "Hair care")
Category.create(name: "Dental care")
Category.create(name: "Stationary")

User.create(name: "FaithForever", email: "faith@test.com", password: "password")